### ISSUE TITLE
What is the difference between cost volume and correlation in FlowNet?

### ISSUE THREAD

**Issue by Zhongdao** [deqings/PWC-Net#1]
Hi Deqing,
I am kind of confused of the cost volume operation in PWC Net, could you please explain a little about the difference between cost volume and correlation in FlowNet ?

Thanks a lot

**Comment by lxtGH** [comment]
Also, in your paper, what does **partial** cost volume mean ?? I am a little confused with the formula ib your paper

**Comment by deqings** [comment]
Sorry for the late reply. Please post your future questions at this address https://github.com/NVlabs/PWC-Net.

Cost volume is a general concept and has been widely used in stereo matching. Correlation in FlowNet is one way to compute the cost volume and is used in our implementation too.

Full cost volume refers to comparing a pixel in the first image with every other pixel in (a large search range of) the second image. By "partial" cost volume we mean computing the cost volume with a small search range around the pixel in the first image. 

Sorry for the confusion. You can refer to our CVPR camera ready, which is more refined compared with the arXiv v1 (Sep. 2017) and v2 (Nov. 2017). https://arxiv.org/pdf/1709.02371.pdf or http://openaccess.thecvf.com/content_cvpr_2018/papers/Sun_PWC-Net_CNNs_for_CVPR_2018_paper.pdf

You may find some clarification in my talks at CVPR 2018 (starts ~7:00 https://www.youtube.com/watch?v=LBJ20kxr1a0) or the robust vision challenge workshop (https://www.youtube.com/watch?v=vVU8XV0Ac_0) too. 

Best regards,
Deqing

**Comment by JiamingSuen** [comment]
@deqings I have a few more questions about cost volume here.

In some other stereo matching networks(e.g. [PSMNet](http://arxiv.org/abs/1803.08669) and [GC-Net](http://arxiv.org/abs/1703.04309)) the cost volume is obtained by concatenating two feature maps and passing them through 3D convolutions. GC-Net claims 3D convolutions to be the better approach to construct cost volums. Besides the cost volume range(partial or full), is this two method(correlation and concat+3D conv) mathematically equivalant(it seems not..)? or "cost volume" is actually a abstract concept with no mathematical definition of it.

Thanks for you answer and this great work!

**Comment by deqings** [comment]
@JiamingSuen. Cost volume is an abstract concept and stores the "cost" (or similarly) of each motion candidate considered for every pixel in the first image. You can compute the cost usingcorrelation, concat + 3D conv, or in other ways (the stereo matching literature has many methods to compute the matching cost, e.g.  http://vision.middlebury.edu/stereo/taxonomy-IJCV.pdf). Hope that helps.
